name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v4
      - name: Build
        run: cd whitelist-upgrade-hasher && cargo b -r --locked
      - name: Compress
        run: |
          mv whitelist-upgrade-hasher/target/release/wuh .
          zstd --ultra -22 -o wuh.zst wuh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wuh
          path: wuh.zst
          retention-days: 1

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Hash
        run: |
          mkdir -p artifacts
          mv wuh/* artifacts/
          cd artifacts
          sha256sum * | tee ../SHA256
          md5sum * | tee ../MD5
          mv ../SHA256 .
          mv ../MD5 .
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          discussion_category_name: Announcements
          generate_release_notes: true
          files: artifacts/*
