name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - name: ocvw
            path: on-chain-version-watcher
          - name: wuh
            path: whitelist-upgrade-hasher
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v4
      - name: Build
        run: cd ${{ matrix.target.path }} && cargo b -r --locked
      - name: Compress
        run: |
          mv ${{ matrix.target.path }}/target/release/${{ matrix.target.name }} .
          zstd --ultra -22 -o ${{ matrix.target.name }}.zst ${{ matrix.target.name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.target.name }}
          path: ${{ matrix.target.name }}.zst
          retention-days: 1

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Hash
        run: |
          mkdir -p artifacts
          mv artifact-*/* artifacts/
          cd artifacts
          sha256sum * | tee ../SHA256
          md5sum * | tee ../MD5
          mv ../SHA256 .
          mv ../MD5 .
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          discussion_category_name: Announcements
          generate_release_notes: true
          files: artifacts/*
